-- 01-table-filmographie.sql
-- Cree la table filmographie et active le controle d'acces (RLS).
-- Prototype d'apprentissage BKL-FOR-003 -- executable tel quel dans le
-- SQL Editor de Supabase, PostgreSQL standard.
--
-- AMENDE le 19/08/2026 23h5x par le greffe, sur demande directe d'AH
-- (incident de chargement : 'generated always as identity' REFUSE un id
-- fourni par le CSV -- Postgres n'accepte alors que ses propres valeurs).
-- Remede : 'generated by default as identity' (l'id du CSV entre, la
-- sequence reste disponible pour le temps 2), + setval APRES import
-- (voir 02-controles.sql, controle 0). Le drop en tete rend le script
-- rejouable apres un essai rate : il REPART DE ZERO.

drop table if exists public.filmographie;

create table public.filmographie (
    id bigint generated by default as identity primary key,
    realisateur text,
    titre text,
    titre_original text,
    categorie text,
    muet boolean not null,
    nb boolean not null,
    duree_min integer null,
    annee integer null,
    annee_source text,
    genres_sc text,
    pays text,
    created_at timestamptz not null default now()
);

-- Active le controle d'acces ligne par ligne : sans policy, personne ne
-- lit ni n'ecrit -- meme pas via la clef anon.
alter table public.filmographie enable row level security;

-- Seule policy : lecture publique (SELECT) pour le role anon.
-- Aucun INSERT, UPDATE ni DELETE public -- c'est la RLS qui protege,
-- pas le secret de la clef anon.
create policy "lecture publique filmographie"
    on public.filmographie
    for select
    to anon
    using (true);
